name: lint
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  
env:
  GOLANGCI_LINT_VERSION: v2.0
  GO_VERSION: "1.23.1"

jobs:
  lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ GO_VERSION }}
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: ${{ GOLANGCI_LINT_VERSION }}

      - uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Thanks for PR'
            })
          