name: lint
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  
env:
  GOLANGCI_LINT_VERSION: "v2.0"
  GO_VERSION: "1.23.1"

jobs:
  lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}