name: release artifacts
on:
  release:
    types:
      - published
  workflow_dispatch:

env:
  GO_VERSION: "1.23.1"

jobs:
  release:
    strategy:
      matrix:
        go-version: [1.23.x]
        os: [ubuntu, windows]
        include:
          - os: ubuntu
            goos: linux
            artifact: ci
            cache_path: |
              ~/.cache/go-build
              ~/go/pkg/mod
          - os: windows
            goos: windows
            artifact: ci.exe
            cache_path: |
              ~\AppData\Local\go-build
              ~\go\pkg\mod

    env:
      GOOS: ${{ matrix.goos }}

    runs-on: ${{ matrix.os }}-latest

    permissions:
      contents: write

    steps:
      - uses: actions/cache@v4
        with:
          path: ${{ matrix.cache_path }}
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-      

      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true
      
      - name: Build app
        run: go build .

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ matrix.artifact }}