name: release artifacts
on:
  release:
    types:
      - published
  workflow_dispatch:

env:
  GO_VERSION: "1.23.1"

jobs:
  release-linux:
    env:
      GOOS: linux

    runs-on: ubuntu-latest

    permissions:
      contents: write


    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true
      
      - name: Build app
        run: go build .

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ci

  release-windows:
    env:
      GOOS: windows
  
    runs-on: windows-latest

    permissions:
      contents: write


    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true
      
      - name: Build app
        run: go build .

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ci.exe