name: tests
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  unit:
    strategy:
      matrix:
        go-version: [1.23.x]
        os: [ubuntu, windows]
        include:
          - os: ubuntu
            cache_path: |
              ~/.cache/go-build
              ~/go/pkg/mod
          - os: windows
            cache_path: |
              ~\AppData\Local\go-build
              ~\go\pkg\mod
    
    runs-on: ${{ matrix.os }}-latest

    steps:
      - uses: actions/cache@v4
        with:
          path: ${{ matrix.cache_path }}
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache: true
      
      - name: Run tests
        run: go test -race -coverprofile coverage.txt -covermode atomic -v